name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "latest"

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: Install dependencies
        run: uv sync

      - name: Code Quality (Linting & Formatting)
        run: uv run ruff check . --exclude "*.ipynb"

      - name: Static Type Checking
        run: uv run mypy --install-types --non-interactive src/ app/

      - name: Run Tests
        run: make test
